"""Single source of truth for the editor's version on the Python side.

Mirrors editor/js/version.js. When bumping the release, edit BOTH files
(and the casc-index.json header gets regenerated by casc_index.py).
"""

VERSION = "0.5.0"
